[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
fs_permissions = [{ access = "read-write", path = "../" }]


[rpc_endpoints]
avalanche-fuji = "https://avalanche-fuji-c-chain-rpc.publicnode.com"

# forge script --chain avalanche-fuji script/Deploy.s.sol:DeployScript --rpc-url $FUJI_TESTNET_RPC --broadcast --verify -vvvv --interactives 1 --verifier-url 'https://api.routescan.io/v2/network/testnet/evm/43113/etherscan' --etherscan-api-key "verifyContract"
